services:
  - type: web
    name: cobertura-oficinas
    env: python
    buildCommand: ""
    startCommand: python teste_modificado_oficial.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
